name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - main

jobs:
  build_application:
    runs-on: ubuntu-latest
    if: github.event_name != 'pull_request' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    name: Build Application
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set Up Node.js 16.x
        uses: actions/setup-node@v1
        with:
          node-version: 16.x

      - name: Install envsubst
        run: sudo apt-get install -y gettext-base

      - name: Replace Environment Variables
        working-directory: .
        env:
          PRODUCTION: 'true'
          API_BASE_URL: ${{ secrets.APIBASEURL }}
          APP_REDIRECT_URI: ${{ secrets.APP_REDIRECT_URI }}
          AZURE_TENANT_ID: ${{ secrets.AZURETENANTID }}
          AZURE_CLIENT_ID: ${{ secrets.AZURECLIENTID }}
          AZURE_API_CLIENT_ID: ${{ secrets.AZUREAPICLIENTID }}
          APP_CONFIG_ENDPOINT: ${{ secrets.APPCONFIGENDPOINT }}
        run: |
          export PRODUCTION=$PRODUCTION
          export API_BASE_URL=$API_BASE_URL
          export APP_REDIRECT_URI=$APP_REDIRECT_URI
          export AZURE_TENANT_ID=$AZURE_TENANT_ID
          export AZURE_CLIENT_ID=$AZURE_CLIENT_ID
          export AZURE_API_CLIENT_ID=$AZURE_API_CLIENT_ID
          export APP_CONFIG_ENDPOINT=$APP_CONFIG_ENDPOINT
          envsubst < src/environments/environment.prod.ts > src/environments/environment.prod.temp.ts
          mv src/environments/environment.prod.temp.ts src/environments/environment.ts

      - name: Install Dependencies
        working-directory: .
        run: |
          npm install
          npm install -g @angular/cli

      - name: Build Application
        working-directory: .
        run: npm run build

      - name: Archive Production Artifact
        uses: actions/upload-artifact@v2
        with:
          name: dist
          path: dist/world-chat-app/

  deploy_application:
    runs-on: ubuntu-latest
    needs: build_application
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    name: Deploy Application
    steps:
      - name: Download Build Artifact
        uses: actions/download-artifact@v2
        with:
          name: dist
          path: dist/world-chat-app/

      - name: Deploy To Azure Static Web Apps
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_ORANGE_TREE_0D3C88E0F }}
          action: "upload"
          app_location: "dist/world-chat-app"
          api_location: ""
          output_location: "dist/world-chat-app"

  close_pull_request:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    name: Close Pull Request
    steps:
      - name: Deploy To Azure Static Web Apps
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_ORANGE_TREE_0D3C88E0F }}
