name: Build and deploy Node.js app to Azure Web App - LingoLink

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: 'Set Up Node.js Version 16'
        uses: actions/setup-node@v1
        with:
          node-version: '16.x'

      - name: 'Create Environment Files'
        run: |
          cp src/environments/environment.ts src/environments/environment.prod.ts
          cp src/environments/environment.ts src/environments/environment.local.ts

      - name: 'Replace Environment Variables'
        run: |
          sed -i "s|#{production}#|true|g" src/environments/environment.prod.ts
          sed -i "s|#{apiBaseUrl}#|${{ secrets.apiBaseUrl }}|g" src/environments/environment.prod.ts
          sed -i "s|#{azureTenantID}#|https://login.microsoftonline.com/${{ secrets.AZURE_TENANT_ID }}|g" src/environments/environment.prod.ts
          sed -i "s|#{azureClientID}#|${{ secrets.azureClientID }}|g" src/environments/environment.prod.ts
          sed -i "s|#{azureAPIClientID}#|${{ secrets.azureAPIClientID }}|g" src/environments/environment.prod.ts
          sed -i "s|#{appConfigEndpoint}#|${{ secrets.appConfigEndpoint }}|g" src/environments/environment.prod.ts

      - name: 'Install Packages/Dependencies'
        run: |
          npm install

      - name: 'Build Application'
        run: |
          npm run build

#      - name: Run tests
#        run: |
#          npm run test

      - name: 'Upload Artifact For Deployment Job'
        uses: actions/upload-artifact@v2
        with:
          name: node-app
          path: .

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: 'Download Artifact From Build Job'
        uses: actions/download-artifact@v2
        with:
          name: node-app

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: 'Deploy To Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'LingoLink'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: .
