name: Build/Deploy Azure Static Web App (Angular Application)

on:
  push:
    branches:
      - main

jobs:
  build_application:
    runs-on: ubuntu-latest
    name: Build Application
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Install Node.js 20.x
        uses: actions/setup-node@v1
        with:
          node-version: 20.x

      - name: Install envsubst
        run: sudo apt-get install -y gettext-base

      - name: Replace Environment Variables
        working-directory: .
        env:
          PRODUCTION: 'true'
          AZURE_TENANT_ID: ${{ secrets.AZURETENANTID }}
          AZURE_CLIENT_ID: ${{ secrets.AZURECLIENTID }}
          AZURE_API_CLIENT_ID: ${{ secrets.AZUREAPICLIENTID }}
        run: |
          export AZURE_TENANT_ID=$AZURE_TENANT_ID
          export AZURE_CLIENT_ID=$AZURE_CLIENT_ID
          export AZURE_API_CLIENT_ID=$AZURE_API_CLIENT_ID
          envsubst < src/environments/environment.prod.ts > src/environments/environment.prod.temp.ts
          mv src/environments/environment.prod.temp.ts src/environments/environment.ts

      - name: Install Dependencies
        working-directory: .
        run: |
          npm install
          npm install -g @angular/cli

      - name: Build Application
        working-directory: .
        run: npm run build:prod

      - name: Run Tests
        run: npm run test --if-present

      - name: Archive Production Artifact
        uses: actions/upload-artifact@v2
        with:
          name: dist
          path: dist/world-chat-app/

  deploy_application:
    runs-on: ubuntu-latest
    needs: build_application
    name: Deploy Application
    environment:
      name: Production
      url: https://orange-tree-0d3c88e0f.3.azurestaticapps.net/ # TODO: PIPE THIS VALUE IN FROM AZURE IN steps.x
    if: (github.event_name == 'push') || (github.event_name == 'pull_request' && github.event.pull_request.merged == true && github.event.pull_request.head.ref != 'dev')
    steps:
      - name: Download Build Artifact
        uses: actions/download-artifact@v2
        with:
          name: dist
          path: dist/world-chat-app/

      - name: Deploy To Azure Static Web Apps
        id: deploy_app_step
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_ORANGE_TREE_0D3C88E0F }}
          action: "upload"
          app_location: "dist/world-chat-app"
          api_location: ""
          output_location: "dist/world-chat-app"
